### ISSUE TITLE
Add `DataFrame.hist()` data to `pandas/profile.py`

### ISSUE THREAD

**Issue by criccomini** [recap-cloud/recap#158]
Add Pandas's `hist()` data to each `Column`:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.hist.html

Follow-on to:

https://github.com/recap-cloud/recap/pull/157

**Comment by nahumsa** [comment]
I would like to work on this issue. Should I add this to the `ColumnProfile`?

https://github.com/recap-cloud/recap/blob/1a064557d9eec68f8902bb70caf631d7cf738ee0/recap/analyzers/pandas/profile.py#L17-L31

**Comment by criccomini** [comment]
Yea, I think a histogram in the column profile sounds right. :) Thanks for picking this up!

**Comment by criccomini** [comment]
So, I noticed `.hist()` actually generates a chart, which isn't what we want. We want a textual representation. Not sure best way to do that.

**Comment by nahumsa** [comment]
Do you think that the result of [`np.hist()`](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html), would be a better fit? It could return a list of values of the histogram and the bin edges of the histogram.

**Comment by criccomini** [comment]
Ah, yea, that looks like the right method to use. Good call.
