### ISSUE TITLE
Usage of Code Linters and Formatters

### ISSUE THREAD

**Issue by nahumsa** [recap-cloud/recap#175]
As discussed in #149, it would be good for the development of the library to have a specific code linter (Pylint, flake8) and/or code formatter (black).

Would you be interested in setting up a linter and formatter for the project?

**Comment by criccomini** [comment]
Yea, definitely. I'm open to suggestions: which do you prefer?

**Comment by nahumsa** [comment]
I really like [black](https://black.readthedocs.io/en/stable/) for formatting and [pylint](https://pylint.readthedocs.io/en/latest/) for linting.

**Comment by criccomini** [comment]
Sounds good. Let's go with that. 🙂

**Comment by nahumsa** [comment]
Pylint gives a "score" for the code and you can enforce a threshold which you accept the changes. Should we enforce that?

**Comment by criccomini** [comment]
Sure! Pick a sane default and we can adjust from there.
