### ISSUE TITLE
Add `pyright` to `style` group

### ISSUE THREAD

**Issue by criccomini** [recap-cloud/recap#181]
We've added isort, black, and pylint. I'm using `pyright` for static type checking in VSCode. I'd like to add that to the style dev-dependencies group, CI, and DEVELOPERS.md as well.

**Comment by criccomini** [comment]
CC @nahumsa

**Comment by nahumsa** [comment]
Awesome! If you don't mind, I can add that :)

**Comment by criccomini** [comment]
Sounds good! Thanks!
