### ISSUE TITLE
Create initial unit tests

### ISSUE THREAD

**Issue by criccomini** [recap-cloud/recap#2]
Recap has no tests right now. 😭  I want to make sure Recap is useful before I go all-in on tests. Some basic unit tests for the crawlers, storage, and API should suffice.

**Comment by nahumsa** [comment]
Hi! I was about to build something similar to this project and I stumbled upon this project! I would be happy to help, and I think that writing some tests is a great way to learn about the project.
Do you have any priority for the unit tests? :)

**Comment by criccomini** [comment]
@nahumsa Hi! Sorry, I missed your comment. I'd love to get some tests in. I think testing the catalog is probably a good place to start; it's the most standalone.

However, before that, we need to figure out which unit test framework to use. Do you have any strong preferences? Seems like `pytest` is what's in most use; does that work for you?

**Comment by criccomini** [comment]
Yup, let's use pytest. And yes, a CI would be great. Shall we use GitHub actions for that?

**Comment by nahumsa** [comment]
Yep, I think that GitHub actions is pretty straight forward to set up and is quite powerful.
