### ISSUE TITLE
Snowflake crawl optimization

### ISSUE THREAD

**Issue by jnoynaert** [recap-cloud/recap#79]
During initial exploration, Snowflake crawler was indexing ~8 tables/minute.

Due to the speed of Snowflake's metadata layer, this could probably benefit from some combination of:

- Source-specific crawl specialization
- Options to "bulk crawl" via e.g. the `SNOWFLAKE` database
- Easy invocation of parallel crawls

P.S. love the project direction

**Comment by criccomini** [comment]
Love the feedback, thanks! Source-specific crawling/analyzing has been on my mind (as have parallel crawls). I need to think a bit about how best to implement it.

For the second bullet-- got a link I can read up on? I'm a BigQuery guy, so my Snowflake-foo is lacking.

**Comment by criccomini** [comment]
@jnoynaert One other note, in the meantime: there are a lot of profilers enabled by default:

```
db.access
db.column
db.comment
db.foreign_key
db.index
db.location
db.primary_key
db.profile
db.view_definitions
```

Many of these don't return anything for Snowflake (e.g. index, primarky_key, foreign_key). You can probably `--exclude` them to speed things up a bit.

**Comment by jnoynaert** [comment]
Excluding profiles make a lot of sense. We actually already do that in other cataloging tools.

Unfortunately the `SNOWFLAKE` account db [doesn't appear to be very well documented](https://docs.snowflake.com/en/sql-reference/snowflake-db.html). Thinking about it some more, though, I don't know if there's a significant improvement in either information availability or speed over just using information schema--probably depends on the exact set of attributes being scraped. Also worth noting that meta database has a lag to populate

**Comment by criccomini** [comment]
@jnoynaert Ah, this is useful information, thanks. Based on what you're saying, I'll probably do a little time-boxed investigation and move on if I can't find anything useful. Some of the usage stuff might be interesting to scrape...
